/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rdf.prototype;
import java.io.*;
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.vocabulary.*;

public class App {
    public static void main (String args[]) {
        String personURI    = "http://amitKumar";
          String givenName    = "Amit";
          String familyName   = "Kumar";
          String fullName     = givenName +" "+ familyName;
  
          Model model = ModelFactory.createDefaultModel();
  
          Resource node = model.createResource(personURI)
                   .addProperty(VCARD.FN, fullName)
                   .addProperty(VCARD.N,
                                model.createResource()
                                     .addProperty(VCARD.Given, givenName)
                                     .addProperty(VCARD.Family, familyName));
          try{
              FileOutputStream fout=new FileOutputStream("/home/fahimfarhan/Codes/Thesis-Codes/rdf-prototype/amitKumar.xml");
              // /home/fahimfarhan/Codes/Thesis-Codes/rdf-prototype
              model.write(fout);
              }catch(IOException e){
                  System.out.println("Exception caught"+e.getMessage());
              }
    }

    public static void start() throws Exception{
        File infile = new File("/home/fahimfarhan/Codes/Thesis-Codes/KnowledgeGraph/Output/output.txt");
        FileOutputStream fout=new FileOutputStream("/home/fahimfarhan/Codes/Thesis-Codes/KnowledgeGraph/Output/myrdf.xml");
              
        FileReader fr = new FileReader(infile);
        BufferedReader br = new BufferedReader(fr);

        String s = "";
        Model model = ModelFactory.createDefaultModel();

        while(true){
            s = br.readLine();
            if(s == null){  break; }
            int lenOfS = s.length();
            s = s.substring(2,lenOfS-3);
            String[] a = s.split("', '");
            Resource node = model.createResource();
                   
                   
            
        }
        br.close();
        fr.close();
        fout.close();
        
    }

}
